python-openapi/openapi-schema-validator

openapi_schema_validator/_format.py

This seems to match RFC 4122
>  Each field is treated as an integer and has its value printed as a zero-filled hexadecimal digit string with the most significant digit first.  The hexadecimal values "a" through "f" are output as lower case characters and are case insensitive on input.

Permit uppercase characters in UUID

---

openapi_schema_validator/validators.py

By giving our created Validator a version, we're also registering it as
one of the global jsonschema validators. From create()'s documentation:
version (str) – an identifier for the version that this validator
class will validate. If provided, the returned validator class will
have its __name__ set to include the version, and also will have
jsonschema.validators.validates automatically called for the given
version.
Why wouldn't we want to do this?
First, this Validator effectively replaces the existing Draft4Validator
because they're both based on the "draft4" schema. Internally, that
means both will be assigned the 'http://json-schema.org/draft-04/schema'
meta-schema, and the second one to be created (ours) will replace the
first in the `jsonschema.validators.meta_schemas` dictionary.
I …

Stop assigning a version to our Validator

---

tests/integration/test_validators.py

`mock` is not installed on Python 3.x according to setup.cfg: `mock; python_version<"3.0"`. Import it from stdlib to fix the ImportError.

Fix mock import in Python 3.x

---

openapi_schema_validator/__init__.py

This makes it easier for automatic license checkers to verify the license of this package.

Use official OSI name in the license metadata

---

openapi_schema_validator/_validators.py
tests/integration/test_validators.py

This would close #14 and #15 at the expense of only being able to validate `required` and  `readOnly/writeOnly` combinations when the `required` is defined on the same schema as the `readOnly/writeOnly` property. 
Personally I would find that more balanced, esp. since `readOnly` and `writeOnly` seem to have been dropped from the latest 3.1.0 OpenAPI specs (cf. https://github.com/OAI/OpenAPI-Specification/issues/1622).
That being said, it might even be more consequent to just resort back to the `jsonschema.validators.required`.

Fix required in composition

---

.gitignore
openapi_schema_validator/validators.py
tests/unit/test_shortcut.py

This PR includes the changes needed to solve issue #24 .
Includes some fixes for tests and unit test for testing the fix included.

[Issue24] Prevent Schema Mutation

---

openapi_schema_validator/validators.py
poetry.lock
pyproject.toml

```python
def iter_errors(self, instance, _schema=None):
if _schema is not None:
warnings.warn(
(
"Passing a schema to Validator.iter_errors "
"is deprecated and will be removed in a future "
"release. Call validator.evolve(schema=new_schema)."
"iter_errors(...) instead."
),
DeprecationWarning,
)
```
https://github.com/Julian/jsonschema/blob/main/jsonschema/validators.py#L189-L198

Fix DeprecationWarning from jsonschema

---

.github/workflows/python-test.yml
README.rst
openapi_schema_validator/__init__.py
openapi_schema_validator/_format.py
openapi_schema_validator/_types.py
openapi_schema_validator/shortcuts.py
openapi_schema_validator/validators.py
tests/integration/test_validators.py

Support for [draft 2020-12](https://json-schema.org/draft/2020-12/json-schema-validation.html) has been added to [jsonschema](https://github.com/Julian/jsonschema) with https://github.com/Julian/jsonschema/pull/817
Since there is no release at the moment, this is only a draft PR as it installs jsonschema directly from github.
The **OAS31Validator** has been added by extending the **Draft202012Validator**. The validator can be used with the `draft202012_format_checker` as seen in the tests.
Python `2.7` and `3.5` have been removed from the test matrix as they are end of life.

p1c2u/openapi-core#296: Implements OpenAPI 3.1 validator

---

openapi_schema_validator/validators.py
poetry.lock
pyproject.toml

This reverts commit c8813cb81695d0adb9d57bc63c20a34d9c147b10, reversing
changes made to b36c12b7356328901b9386e8b7f71d4bf2369a71.
Removing the change from `0.2.x` branch i will go to `0.3.x` that will support jsonschema 4+
Fixes #31

Revert "make jsonschema4 compatible (DeprecationWarning fix)"

---

poetry.lock
pyproject.toml

limit jsonschema dependency for version `0.2.x` to `3.0.0-4.x.x`
Related to #22

Limit jsonschema dependency

---

openapi_schema_validator/validators.py
poetry.lock
pyproject.toml

Reintroduces #25 after revert #34
This reverts commit 6ae997f3dea1302c1b53dc0b46f78f2bfffc3b4f, reversing
changes made to 22c58927086b27cce6deb68af3a418e8f4ce5976.

make jsonschema4 compatible (DeprecationWarning fix) reintroduced

---

openapi_schema_validator/_validators.py
openapi_schema_validator/validators.py
tests/integration/test_validators.py

Related to: #29.
Implement discriminator support.
Todo:

Validate oneOf, anyOf and allOf with discriminator

---

openapi_schema_validator/validators.py
tests/integration/test_validators.py

readOnly and writeOnly on jsonschema4 fix

---

README.rst

References README update

---

openapi_schema_validator/validators.py

oas30validator subclassing workaround

---

pyproject.toml

The last usage of attrs has been dropped in 22b12e7, but attrs is still marked as runtime dependency in pyproject.toml.
Fixes: https://github.com/p1c2u/openapi-schema-validator/issues/53

Drop no longer used runtime dependency on attrs

---

README.rst

I just happen to have access to this repository, but I am reporting that I found a typo in the README.

fix: typo in docs

---

openapi_schema_validator/_validators.py
openapi_schema_validator/validators.py
tests/integration/test_validators.py

Hi,
Thank you for the fantastic work on a schema validator. This project has helped me significantly in validating dynamically generated openapi schemas.
Please consider merging this small improvement in handling nullable behavior.
The root of #20 seems to be that if a schema node is a meta node ($ref, allOf, anyOf, or oneOf), nullable shouldn't be checked.
The tests added validate both that null is allows when nullable:true the destination schema, and not allowed when nullable:false is on the destination schemas.

Fix #20 - nullable semantics with $ref, oneOf, anyOf, and allOf

---

.github/workflows/python-test.yml
openapi_schema_validator/_format.py
openapi_schema_validator/validators.py
pyproject.toml
tests/integration/test_validators.py

Rely on jsonschema `date` `date-time` and `uuid` format checkers

format checkers assigned to validators

---

.github/workflows/python-test.yml
openapi_schema_validator/validators.py
poetry.lock
pyproject.toml
tests/integration/test_validators.py

test required formats only

---

openapi_schema_validator/_format.py
tests/integration/test_validators.py

Formats raise error for other types fix

---

openapi_schema_validator/_keywords.py
openapi_schema_validator/validators.py
poetry.lock
pyproject.toml

Jsonschema keywords module rename fix

---

openapi_schema_validator/_keywords.py
openapi_schema_validator/validators.py
tests/integration/test_validators.py

OAS30Validator readonly writeonly fix
